In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [2]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000, n_features=3,  n_redundant=1, n_classes=2, random_state=999)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [31]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=9, algorithm='auto', metric='minkowski', p=2, weights='uniform')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [32]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
score = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)
print("Accuracy Score:", score)
print("Confusion Matrix:\n", cm)
print("Classification Report:\n", cr)

Accuracy Score: 0.935
Confusion Matrix:
 [[98  5]
 [ 8 89]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.95      0.94       103
           1       0.95      0.92      0.93        97

    accuracy                           0.94       200
   macro avg       0.94      0.93      0.93       200
weighted avg       0.94      0.94      0.93       200



In [33]:
model = KNeighborsClassifier()
params = {  
    'n_neighbors': [3, 5, 7, 9, 11, 13, 15, 17, 19, 21],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'metric': ['euclidean', 'manhattan', 'minkowski'],
    'p': [1, 2],
    'weights': ['uniform', 'distance']
}


In [35]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()
grid = GridSearchCV(estimator=model, param_grid=params, cv=cv, scoring='accuracy', n_jobs=-1)
grid.fit(X_train, y_train)
y_pred = grid.predict(X_test)

In [37]:
grid.best_params_

{'algorithm': 'auto',
 'metric': 'euclidean',
 'n_neighbors': 5,
 'p': 1,
 'weights': 'uniform'}

In [36]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
score = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)
print("Accuracy Score:", score)
print("Confusion Matrix:\n", cm)
print("Classification Report:\n", cr)

Accuracy Score: 0.915
Confusion Matrix:
 [[98  5]
 [12 85]]
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.95      0.92       103
           1       0.94      0.88      0.91        97

    accuracy                           0.92       200
   macro avg       0.92      0.91      0.91       200
weighted avg       0.92      0.92      0.91       200



In [40]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, StratifiedKFold

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier())
])

params = {
    'knn__n_neighbors': list(range(3, 32, 2)),
    'knn__metric': ['minkowski'],      # p=1 -> manhattan, p=2 -> euclidean
    'knn__p': [1, 2],
    'knn__weights': ['uniform', 'distance'],
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
grid = GridSearchCV(pipe, params, cv=cv, scoring='accuracy', n_jobs=-1)
grid.fit(X_train, y_train)
y_pred = grid.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
score = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)
print("Accuracy Score:", score)
print("Confusion Matrix:\n", cm)
print("Classification Report:\n", cr)

Accuracy Score: 0.925
Confusion Matrix:
 [[98  5]
 [10 87]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.95      0.93       103
           1       0.95      0.90      0.92        97

    accuracy                           0.93       200
   macro avg       0.93      0.92      0.92       200
weighted avg       0.93      0.93      0.92       200



In [38]:
# Regression

In [42]:
from sklearn.datasets import make_regression
from sklearn.neighbors import KNeighborsRegressor
X, y = make_regression(n_samples=1000, n_features=3, noise=0.1, random_state=999)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [43]:
regressor = KNeighborsRegressor(n_neighbors=6, algorithm='auto', metric='minkowski', p=2, weights='uniform')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [45]:
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=np.sqrt(mse)
print(mse)
print(mae)
print(rmse)
print("R-squared:", r2_score(y_test, y_pred))

252.5887876453374
9.57347565406974
15.893042114250418
R-squared: 0.962621904327832
